# Generated by Django 3.0.6 on 2020-05-21 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('unit', models.CharField(max_length=5, verbose_name='Единица измерения')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('kol', models.IntegerField(default=0, verbose_name='Количество в магазине')),
                ('date', models.DateField(verbose_name='Дата изготовления товара')),
                ('img', models.ImageField(upload_to='tovar/', verbose_name='Изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер накладной')),
                ('date', models.DateField(verbose_name='Дата покупки')),
                ('kol', models.IntegerField(verbose_name='Количество купленного')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Tovar', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('kol', models.IntegerField(default=0, verbose_name='Количество товара для доставки')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Tovar', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
            },
        ),
    ]
