# Generated by Django 2.2.13 on 2020-06-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200609_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kol',
        ),
        migrations.RemoveField(
            model_name='order',
            name='number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tovar',
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kol', models.IntegerField(verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Order', verbose_name='Покупка')),
                ('tovar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Tovar', verbose_name='Товар')),
            ],
        ),
    ]
