# Generated by Django 2.2.13 on 2020-06-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contacts',
            field=models.TextField(default=''),
        ),
    ]
